<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Xibo Admin - Installation</title>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<link rel="stylesheet" type="text/css" href="template/css/login_box.css" />
	
	<link rel="shortcut icon" href="img/favicon.ico" />
	
	<script type="text/javascript">
		$(document).ready(function(){
		
			document.getElementById('username').focus();
			
		});
	</script>

</head>

<body>

<div id="container">

	<div id="content">

		<div class="login_box">
			
			<div class="login_header">
				<div class="login_header_left">
				</div>

				<div class="login_header_right">
				</div>
			</div>
			
			<div class="login_body">
