POST {{url}}/xmds.php?v=7
Content-Type: application/xml

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:tns="urn:xmds" xmlns:types="urn:xmds/encodedTypes"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <soap:Body soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <tns:RegisterDisplay>
      <serverKey xsi:type="xsd:string">{{serverKey}}</serverKey>
      <hardwareKey xsi:type="xsd:string">{{hardwareKey}}</hardwareKey>
      <displayName xsi:type="xsd:string">{{displayName}}</displayName>
      <clientType xsi:type="xsd:string">{{clientType}}</clientType>
      <clientVersion xsi:type="xsd:string">4</clientVersion>
      <clientCode xsi:type="xsd:int">400</clientCode>
      <macAddress xsi:type="xsd:string">{{macAddress}}</macAddress>
      <licenceResult xsi:type="xsd:string">trial</licenceResult>
      <xmrChannel xsi:type="xsd:string">XMR_test_channel</xmrChannel>
      <xmrPubKey xsi:type="xsd:string">-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8tUH0MqtiB7Hq7a+Au0v
3MHFDnlwBmSz9S+44dGir0d119pbZQKb1D5JaGTWsBq0Ca4yAW/XtDwL5Olbue8n
y2PBygUArJulUQdCeguAKmHCcRw6rce0ZsQymUe84dclf9l7yyCbo1VTDBH651UT
a/ei6ATBPeLhh98lDKDpz/RmsXuW695thxhTRXPIILDDKYkK5yQF2DNEgVoShFjG
TRys5AL2ZUrGHrrT5dxOfbNE0sU8qvoYVQIjyUVhANzh66bu8QTbjDcRLMiKE1lJ
l5U/XOnNkKi+qNimFWRKlNS0sOvPdTJHHZZEaoFa2FXGYGL8/XAidwT6YSY702Gb
8wIDAQAB
-----END PUBLIC KEY-----</xmrPubKey>
    </tns:RegisterDisplay>
  </soap:Body>
</soap:Envelope>

###

POST {{url}}/xmds.php?v=7
Content-Type: application/xml

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:tns="urn:xmds" xmlns:types="urn:xmds/encodedTypes"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <soap:Body soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <tns:RequiredFiles>
      <serverKey xsi:type="xsd:string">{{serverKey}}</serverKey>
      <hardwareKey xsi:type="xsd:string">{{hardwareKey}}</hardwareKey>
    </tns:RequiredFiles>
  </soap:Body>
</soap:Envelope>

###

POST {{url}}/xmds.php?v=7
Content-Type: application/xml

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:tns="urn:xmds" xmlns:types="urn:xmds/encodedTypes"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <soap:Body soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <tns:Schedule>
      <serverKey xsi:type="xsd:string">{{serverKey}}</serverKey>
      <hardwareKey xsi:type="xsd:string">{{hardwareKey}}</hardwareKey>
    </tns:Schedule>
  </soap:Body>
</soap:Envelope>

###

POST {{url}}/xmds.php?v=7
Content-Type: application/xml

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:tns="urn:xmds" xmlns:types="urn:xmds/encodedTypes"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <soap:Body soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <tns:GetDependency>
      <serverKey xsi:type="xsd:string">{{serverKey}}</serverKey>
      <hardwareKey xsi:type="xsd:string">{{hardwareKey}}</hardwareKey>
      <fileType xsi:type="xsd:string">bundle</fileType>
      <id xsi:type="xsd:int">1</id>
    </tns:GetDependency>
  </soap:Body>
</soap:Envelope>

###

POST {{url}}/xmds.php?v=7
Content-Type: application/xml

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:tns="urn:xmds" xmlns:types="urn:xmds/encodedTypes"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <soap:Body soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <tns:GetData>
      <serverKey xsi:type="xsd:string">{{serverKey}}</serverKey>
      <hardwareKey xsi:type="xsd:string">{{hardwareKey}}</hardwareKey>
      <widgetId xsi:type="xsd:int">{{testWidgetId}}</widgetId>
    </tns:GetData>
  </soap:Body>
</soap:Envelope>

###

# Get the fileID from the Required Files response.
GET {{url}}/xmds.php?file=6fdcddfc0c386f5abce4f8c8b5983b1a&displayId=1&type=P&itemId=1&fileType=fontCss

###

GET {{url}}/xmds.php?file=6fdcddfc0c386f5abce4f8c8b5983b1a&displayId=1&type=P&itemId=4&fileType=font
