<?php
/*
 * Copyright (C) 2026 Xibo Signage Ltd
 *
 * Xibo - Digital Signage - https://xibosignage.com
 *
 * This file is part of Xibo.
 *
 * Xibo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * Xibo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Xibo.  If not, see <http://www.gnu.org/licenses/>.
 */
namespace Xibo\Helper;

/**
 * Resolves Vite asset URLs from the manifest generated by `vite build`.
 *
 * In production: reads web/prototype/.vite/manifest.json and returns hashed asset paths.
 * In dev mode (manifest absent): returns Vite dev server URLs so HMR works.
 */
class ViteManifest
{
    private const MANIFEST = PROJECT_ROOT . '/web/prototype/.vite/manifest.json';
    private const DEV_BASE = 'http://localhost:5173';
    private const PROD_BASE = '/prototype/';

    private static ?array $data = null;
    private static bool $loaded = false;

    /**
     * Returns the JS bundle URL for the given Vite entry point.
     *
     * In dev mode Vite's dev server serves all project files under its base path
     * (/prototype/), so the source file must be requested as
     * http://localhost:5173/prototype/src/login/main.tsx — not /src/login/main.tsx.
     * Without the base prefix the request hits Vite's proxy and gets forwarded to
     * PHP, which 404s it.
     *
     * @throws \RuntimeException if manifest present but entry not found
     */
    public static function getJsUrl(string $entry): string
    {
        if (self::isDevMode()) {
            $devEntryMap = [
                'login.html' => 'src/login/main.tsx',
                'index.html' => 'src/main.tsx',
            ];
            $src = $devEntryMap[$entry] ?? ltrim($entry, '/');
            // Include the Vite base (/prototype/) so the path is not caught by the proxy.
            return self::DEV_BASE . self::PROD_BASE . $src;
        }

        $file = self::load()[$entry]['file'] ?? null;
        if ($file === null) {
            throw new \RuntimeException('Vite manifest: entry \'' . $entry . '\' not found');
        }

        return self::PROD_BASE . $file;
    }

    /**
     * Returns the Vite HMR client URL for embedding in PHP-served shells, or null
     * in production (no dev server running).
     *
     * Same base-prefix rule as getJsUrl: @vite/client must be requested at
     * /prototype/@vite/client so Vite handles it rather than proxying it to PHP.
     */
    public static function getClientUrl(): ?string
    {
        if (!self::isDevMode()) {
            return null;
        }
        return self::DEV_BASE . self::PROD_BASE . '@vite/client';
    }

    /**
     * Returns the @react-refresh URL for the Fast Refresh preamble, or null in production.
     *
     * @vitejs/plugin-react transforms every component to use Fast Refresh and checks
     * window.__vite_plugin_react_preamble_installed__ at runtime. When Vite serves the
     * HTML it injects this preamble automatically; PHP-served shells must do it manually
     * by importing @react-refresh, calling injectIntoGlobalHook(), and setting the flag
     * before any React module loads.
     */
    public static function getRefreshUrl(): ?string
    {
        if (!self::isDevMode()) {
            return null;
        }
        return self::DEV_BASE . self::PROD_BASE . '@react-refresh';
    }

    /**
     * Returns the CSS bundle URL for the given entry point, or null.
     * In dev mode Vite injects CSS via JS — no separate CSS URL is needed.
     */
    public static function getCssUrl(string $entry): ?string
    {
        if (self::isDevMode()) {
            return null;
        }

        $css = self::load()[$entry]['css'][0] ?? null;
        return $css !== null ? self::PROD_BASE . $css : null;
    }

    /**
     * True when the Vite manifest is absent (i.e. `npm run dev` is active).
     */
    public static function isDevMode(): bool
    {
        self::load();
        return self::$data === null;
    }

    private static function load(): array
    {
        if (!self::$loaded) {
            self::$loaded = true;
            if (file_exists(self::MANIFEST)) {
                $raw = file_get_contents(self::MANIFEST);
                self::$data = $raw !== false ? (json_decode($raw, true) ?? []) : [];
            }
        }
        return self::$data ?? [];
    }
}
