name: Build PR

on:
  pull_request:
#  pull_request_review:
#    types: [submitted]

jobs:
  build:
    name: Build PR container
    if: github.repository == 'xibosignage/xibo-cms'
    #    if: github.repository == 'xibosignage/xibo-cms' && github.event.review.state == 'APPROVED'
    runs-on: ubuntu-22.04

    steps:
      - uses: octokit/request-action@v2.x
        id: build_pr
        with:
          route: POST /repos/{owner}/{repo}/dispatches
          owner: xibosignageltd
          repo: qa
          pr_number: ${{ github.event.pull_request.number }}
          sha: ${{ github.event.head.sha }}
          issue_number: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}