name: Build Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Containers
    if: github.repository == 'xibosignage/xibo-cms'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure Build X
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/xibosignage/xibo-cms:release-${{ github.ref_name }}
          build-args: GIT_COMMIT=${{ github.sha }}
          push: true
          load: false

      - name: Pull Image
        run: |
          docker pull ghcr.io/xibosignage/xibo-cms:release-${GITHUB_REF##*/}

      - name: Build archive
        run: |
          CONTAINER=$(docker create ghcr.io/xibosignage/xibo-cms:release-${GITHUB_REF##*/})
          echo 'Copying from container.'
          docker cp "$CONTAINER":/var/www/cms/ xibo-cms-${GITHUB_REF##*/}
          tar -czf xibo-cms-${GITHUB_REF##*/}.tar.gz xibo-cms-${GITHUB_REF##*/}
          zip -rq xibo-cms-${GITHUB_REF##*/}.zip xibo-cms-${GITHUB_REF##*/}
          echo 'Added to archives.'
          docker rm "$CONTAINER"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          fail_on_unmatched_files: true
          files: |
            **.tar.gz
            **.zip
