name: Build Container

on:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    name: Build PR container
    if: github.repository == 'xibosignage/xibo-cms' && github.event.review.state == 'APPROVED'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Configure Build X
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Container
        uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/xibosignage/xibo-cms:test-${{ github.event.number }}
          build-args: GIT_COMMIT=${{ github.ref_name }}
          push: true
          load: false
