name: "PHPCS"

on:
  pull_request:
    paths:
      - "**.php"
      - ".github/workflows/phpcs.yml"
    branches-ignore:
      - master

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!

      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - name: Get our latest coding standards
        run: |
          curl -OL https://raw.githubusercontent.com/xibosignage/support/master/src/Standards/xibo_ruleset.xml

      - uses: thenabeel/action-phpcs@v8
        with:
          files: "**.php"
          phpcs_path: php phpcs.phar
          standard: xibo_ruleset.xml